# Site settings
title: WnCC
header-img: img/home-bg.jpg
email: cheekujodhpur@gmail.com
description: "The Official WnCC@IITB blog"
baseurl: ""
url: "http://wncc-iitb.com"
twitter_username: 
github_username:  wncc
facebook_username:  wncc.iitb

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["sample", "less","node_modules","Gruntfile.js","package.json","README.md"]
